CREATE PROC FI_SP_VerificaBeneficiario
	@CPF VARCHAR
AS
BEGIN
	IF(ISNULL(@CPF,'') = '')
		SELECT CPF, NOME, IDLCIENTE FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT CPF, NOME, IDLCIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF
END